spring:
  application:
    name: facility-client

server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  security:
    enabled: false

logging:
  file: client.log